/* Generated by './build/bin/build-entry.js' */

import ForgotPasswordForm from './forgot-password-form'
import LoginForm from './login-form'
import RegisterForm from './register-form'

export {
  ForgotPasswordForm,
  LoginForm,
  RegisterForm
}
