/* Generated by './build/bin/build-entry.js' */

import Aside from './aside'
import Container from './container'
import Footer from './footer'
import Header from './header'
import Main from './main'

export {
  Aside,
  Container,
  Footer,
  Header,
  Main
}
